EmployeeManagement/EmployeeManagement.WebUI/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EmployeeManagement.Core.Models;
using EmployeeManagement.Core.Interfaces.Services;
using AutoMapper;
using EmployeeManagement.WebUI.ViewModels;
using EmployeeManagement.Infrastructure;

namespace EmployeeManagement.WebUI.Controllers
{    
    public class AdminController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly ITodoService _todoService;
        private readonly IMapper _mapper;

        public AdminController(IEmployeeService employeeService, ITodoService todoService, IMapper mapper)
        {
            this._employeeService = employeeService;
            this._todoService = todoService;
            this._mapper = mapper;
        }
        
        [HttpGet]
        public async Task<IActionResult> ListEmployees()
        {
            List<Employee> employees = await _employeeService.GetAllEmployeesAsync(false);
            return View(employees);
        }

        [HttpGet]
        public IActionResult CreateEmployee()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateEmployee(CreateEmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                Employee employee = _mapper.Map<CreateEmployeeViewModel, Employee>(model);
                await _employeeService.CreateEmployeeAsync(employee, model.Photo);
                TempData["message"] = $"Employee {employee.Name} " +
                    $"was succesfully created!";

                return RedirectToAction(nameof(ListEmployees));
            }
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> EditEmployee(int employeeId)
        {
            try
            {
                Employee employee = await _employeeService.GetEmployeeByIdAsync(employeeId, true);
                EditEmployeeViewModel model = _mapper.Map<Employee, EditEmployeeViewModel>(employee);
                return View(model);
            }
            catch(ItemNotFoundException exc)
            {
                Response.StatusCode = 404;
                ViewBag.ErrorMessage = exc.Message;
                return View("NotFound");
            }            
        }

        [HttpPost]
        public async Task<IActionResult> EditEmployee(EditEmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Employee employee = _mapper.Map<EditEmployeeViewModel, Employee>(model);
                    await _employeeService.UpdateEmployeeAsync(employee, model.Photo);
                    TempData["message"] = $"Employee with ID = {employee.Id} " +
                            $"was succesfully updated!";
                    return RedirectToAction(nameof(ListEmployees));
                }
                catch(ItemNotFoundException exc)
                {
                    Response.StatusCode = 404;
                    ViewBag.ErrorMessage = exc.Message;
                    return View("NotFound");
                }
            }
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> EditEmployeeTodos(int employeeId)
        {
            try
            {
                Employee employee = await _employeeService.GetEmployeeByIdAsync(employeeId, true);
                EditEmployeeTodosViewModel model = _mapper.Map<Employee, EditEmployeeTodosViewModel>(employee);
                ViewBag.AllTodos = await _todoService.GetAllTodosAsync(false);
                return View(model);
            }
            catch (ItemNotFoundException exc)
            {
                Response.StatusCode = 404;
                ViewBag.ErrorMessage = exc.Message;
                return View("NotFound");
            }            
        }
        
        [HttpPost]
        public async Task<IActionResult> EditEmployeeTodos(int employeeId, string employeeName, int[] todosIds)
        {
            try
            {
                await _employeeService.ManageEmployeeTodosAsync(employeeId, todosIds);
                TempData["message"] = $"{employeeName}'s todos " +
                            $"were succesfully managed!";
                return RedirectToAction(nameof(EditEmployee), new { employeeId = employeeId });
            }
            catch(ItemNotFoundException exc)
            {
                Response.StatusCode = 404;
                ViewBag.ErrorMessage = exc.Message;
                return View("NotFound");
            }            
        }

        [HttpPost]
        public async Task<IActionResult> DeleteEmployee(int employeeId)
        {
            try
            {
                await _employeeService.DeleteEmployeeAsync(employeeId);
                TempData["message"] = $"Employee with ID={employeeId} " +
                        $"was succesfully deleted!";

                return RedirectToAction(nameof(ListEmployees));
            }
            catch (ItemNotFoundException exc)
            {
                Response.StatusCode = 404;
                ViewBag.ErrorMessage = exc.Message;
                return View("NotFound");
            }
            
        }

        [HttpGet]
        public async Task<IActionResult> ListTodos()
        {
            List<Todo> todos = await _todoService.GetAllTodosAsync(false);
            return View(todos);
        }

        [HttpGet]
        public IActionResult CreateTodo()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateTodo(CreateTodoViewModel model)
        {
            if (ModelState.IsValid)
            {
                Todo todo = _mapper.Map<CreateTodoViewModel, Todo>(model);
                await _todoService.CreateTodoAsync(todo);
                TempData["message"] = $"Todo {todo.Name} " +
                    $"was succesfully created!";

                return RedirectToAction(nameof(ListTodos));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditTodo(int todoId)
        {
            try
            {
                Todo todo = await _todoService.GetTodoByIdAsync(todoId, true);
                EditTodoViewModel model = _mapper.Map<Todo, EditTodoViewModel>(todo);
                return View(model);
            }
            catch (ItemNotFoundException exc)
            {
                Response.StatusCode = 404;
                ViewBag.ErrorMessage = exc.Message;
                return View("NotFound");
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditTodo(EditTodoViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Todo todo = _mapper.Map<EditTodoViewModel, Todo>(model);
                    await _todoService.UpdateTodoAsync(todo);
                    TempData["message"] = $"Todo with ID = {todo.Id} " +
                            $"was succesfully updated!";
                    return RedirectToAction(nameof(ListTodos));
                }
                catch (ItemNotFoundException exc)
                {
                    Response.StatusCode = 404;
                    ViewBag.ErrorMessage = exc.Message;
                    return View("NotFound");
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditTodoEmployees(int todoId)
        {
            try
            {
                Todo todo = await _todoService.GetTodoByIdAsync(todoId, true);
                EditTodoEmployeesViewModel model = _mapper.Map<Todo, EditTodoEmployeesViewModel>(todo);
                ViewBag.AllEmployees = await _employeeService.GetAllEmployeesAsync(false);
                return View(model);
            }
            catch (ItemNotFoundException exc)
            {
                Response.StatusCode = 404;
                ViewBag.ErrorMessage = exc.Message;
                return View("NotFound");
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditTodoEmployees(int todoId, string todoName, int[] employeesIds)
        {
            try
            {
                await _todoService.ManageEmployeesOnTodoAsync(todoId, employeesIds);
                TempData["message"] = $"Employees assigned to todo \"{todoName}\" " +
                            $"were succesfully managed!";
                return RedirectToAction(nameof(EditTodo), new { todoId = todoId });
            }
            catch (ItemNotFoundException exc)
            {
                Response.StatusCode = 404;
                ViewBag.ErrorMessage = exc.Message;
                return View("NotFound");
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteTodo(int todoId)
        {
            try
            {
                await _todoService.DeleteTodoAsync(todoId);
                TempData["message"] = $"Todo with ID={todoId} " +
                        $"was succesfully deleted!";

                return RedirectToAction(nameof(ListTodos));
            }
            catch (ItemNotFoundException exc)
            {
                Response.StatusCode = 404;
                ViewBag.ErrorMessage = exc.Message;
                return View("NotFound");
            }
        }
    }
}

EmployeeManagement/EmployeeManagement.WebUI/Views/Shared/Forbidden.cshtml
@{
    ViewBag.Title = "403 Error";
}

<div class="container">
    <div class="mt-3 text-center">
        <h1 class="text-danger">Forbidden</h1>
        <h6 class="text-danger">You do not have persmission to access this resource</h6>
        <img src="~/images/forbidden.png" style="height:300px; width:300px" />
    </div>
</div>

EmployeeManagement/EmployeeManagement.WebUI/Views/Shared/NotFound.cshtml
<div class="container">
    <h1>@ViewBag.ErrorMessage</h1>
    <a asp-action="index" asp-controller="home">
       Click here to navigate to the home page
    </a>
</div>

EmployeeManagement/EmployeeManagement.WebUI/Views/Shared/Unauthorized.cshtml
@{
    ViewBag.Title = "401 Error";
}

<div class="container">
    <div class="mt-3 text-center">
        <h1 class="text-danger">Unauthorized</h1>
        <h6 class="text-danger">No unauthorized entry</h6>
        <img src="~/images/unauthorized.png" style="height:300px; width:300px" />
    </div>
</div>

EmployeeManagement/EmployeeManagement.WebUI/Views/Shared/_ConfirmDeletionPartial.cshtml
<div class="modal fade" id="confirmDeletionModal">
    <div class="modal-dialog modal-dialog-centered modal-sm">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title w-100 text-center">Confirm Deletion</h4>
            </div>

            <div class="modal-body w-100 text-center"></div>

            <div class="modal-footer">
                <div class="w-100 text-center">
                    <button id="delete" type="button" class="btn btn-danger mr-1">Yes</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</div>

EmployeeManagement/EmployeeManagement.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <environment include="Development">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              asp-suppress-fallback-integrity="true">
    </environment>
    <link href="~/css/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a href="#" class="navbar-brand">
            @ViewBag.Title
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link"
                       asp-controller="home"
                       asp-action="index">
                        Home
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Manage
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" asp-controller="Admin"
                           asp-action="ListEmployees">Employees</a>
                        <a class="dropdown-item" asp-controller="Admin"
                           asp-action="ListTodos">Todos</a>
                    </div>
                </li>
            </ul>            
        </div>
    </nav>

    <div>
        <div class="container">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success mt-1">@TempData["message"]</div>
            }
        </div>
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
                crossorigin="anonymous">
        </script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous">
        </script>
    </environment>

    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: false)
    }
</body>
</html>